### ISSUE TITLE
关于类的命名

### ISSUE THREAD

**Issue by YanGuam** [Mogara/QSanguosha#210]
QSan开头的类应该换成M开头。否则和Qt自身的类太像了，看着这几个QSGS开头的就觉得很惊悚。。

![qq 20150106021641](https://cloud.githubusercontent.com/assets/3531837/5617470/26fbeb4a-954a-11e4-9e4b-fe0bfc90fd65.png)

如果以后Qt出了QSan开头的类。。简直不堪设想
（以后开issue记录一些重要的聊天记录）

**Comment by Moligaloo** [comment]
用 namespace 不是更好么？

**Comment by YanGuam** [comment]
现在的namespace是可选的，只要用户定义MCD_BEGIN_NAMESPACE宏，指定一个名称就行。
