### ISSUE TITLE
build error   使用VS2013(Windows)

### ISSUE THREAD

**Issue by lushaoxun** [Mogara/QSanguosha#224]
编译时出现这样的错误，共有720个这样的错误
 1>AboutUs.obj : error LNK2001: 无法解析的外部符号 "class Engine * Sanguosha" (?Sanguosha@@3PAVEngine@@A)
1>banipdialog.obj : error LNK2001: 无法解析的外部符号 "public: class QString __thiscall Player::getState(void)const " (?getState@Player@@QBE?AVQString@@XZ)
1>banipdialog.obj : error LNK2001: 无法解析的外部符号 "public: class QString __thiscall Player::screenName(void)const " (?screenName@Player@@QBE?AVQString@@XZ)
1>banipdialog.obj : error LNK2001: 无法解析的外部符号 "class Settings * SettingsInstance" (?SettingsInstance@@3PAVSettings@@A)
1>banlistdialog.obj : error LNK2001: 无法解析的外部符号 "public: static class QSet<struct BanPair> const __cdecl BanPair::getBanPairSet(void)" (?getBanPairSet@BanPair@@SA?BV?$QSet@UBanPair@@@@XZ)
1>banlistdialog.obj : error LNK2001: 无法解析的外部符号 "public: static void __cdecl BanPair::loadBanPairs(void)" (?loadBanPairs@BanPair@@SAXXZ)
1>FreeChooseDialog.obj : error LNK2001: 无法解析的外部符号 "public: class QList<class General const *> __thiscall Engine::getGeneralList(void)const " (?getGeneralList@Engine@@QBE?AV?$QList@PBVGeneral@@@@XZ)
      请指点，谢谢您了。

**Comment by Fsu0413** [comment]
这个repo已经放弃维护。

**Comment by Fsu0413** [comment]
@sunnylife 来关了这个issue吧
